"""inventory_schema

Revision ID: 629b0e3922ce
Revises: 8c6218e0d8f9
Create Date: 2026-07-23 22:39:34.830568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '629b0e3922ce'
down_revision: Union[str, Sequence[str], None] = '8c6218e0d8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_allocation_logs',
    sa.Column('allocation_number', sa.String(length=100), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('allocated_quantity', sa.Float(), nullable=False),
    sa.Column('allocated_by', sa.String(length=255), nullable=True),
    sa.Column('allocation_status', sa.Enum('PENDING', 'ALLOCATED', 'RELEASED', name='allocationstatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('allocated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['material_requests.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('allocation_number')
    )
    op.create_index(op.f('ix_material_allocation_logs_id'), 'material_allocation_logs', ['id'], unique=False)
    op.create_index(op.f('ix_material_allocation_logs_material_id'), 'material_allocation_logs', ['material_id'], unique=False)
    op.create_index(op.f('ix_material_allocation_logs_warehouse_id'), 'material_allocation_logs', ['warehouse_id'], unique=False)
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_inventory_stock_id'), table_name='inventory_stock')
    op.drop_table('inventory_stock')
    op.drop_index(op.f('ix_production_jobs_id'), table_name='production_jobs')
    op.drop_table('production_jobs')
    op.alter_column('goods_receipt_items', 'rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(op.f('goods_receipt_items_material_id_fkey'), 'goods_receipt_items', type_='foreignkey')
    op.create_foreign_key(None, 'goods_receipt_items', 'materials', ['material_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_index(op.f('ix_goods_receipts_grn_number'), table_name='goods_receipts')
    op.create_unique_constraint(None, 'goods_receipts', ['grn_number'])
    op.drop_constraint(op.f('goods_receipts_warehouse_id_fkey'), 'goods_receipts', type_='foreignkey')
    op.create_foreign_key(None, 'goods_receipts', 'warehouses', ['warehouse_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.add_column('inventory', sa.Column('warehouse_id', sa.UUID(), nullable=False))
    op.add_column('inventory', sa.Column('available_quantity', sa.Float(), nullable=False))
    op.add_column('inventory', sa.Column('reserved_quantity', sa.Float(), nullable=False))
    op.add_column('inventory', sa.Column('minimum_stock', sa.Float(), nullable=True))
    op.add_column('inventory', sa.Column('maximum_stock', sa.Float(), nullable=True))
    op.add_column('inventory', sa.Column('reorder_level', sa.Float(), nullable=True))
    op.add_column('inventory', sa.Column('storage_location', sa.String(length=255), nullable=True))
    op.add_column('inventory', sa.Column('unit_cost', sa.Float(), nullable=True))
    op.add_column('inventory', sa.Column('last_stock_update', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('inventory_material_id_key'), 'inventory', type_='unique')
    op.create_index(op.f('ix_inventory_material_id'), 'inventory', ['material_id'], unique=False)
    op.create_index(op.f('ix_inventory_warehouse_id'), 'inventory', ['warehouse_id'], unique=False)
    op.create_unique_constraint('uq_inventory_material_warehouse', 'inventory', ['material_id', 'warehouse_id'])
    op.drop_constraint(op.f('inventory_material_id_fkey'), 'inventory', type_='foreignkey')
    op.create_foreign_key(None, 'inventory', 'warehouses', ['warehouse_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'inventory', 'materials', ['material_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_column('inventory', 'quantity')
    op.drop_column('inventory', 'warehouse_location')
    op.add_column('inventory_transactions', sa.Column('transaction_number', sa.String(length=100), nullable=False))
    op.add_column('inventory_transactions', sa.Column('performed_by', sa.String(length=255), nullable=True))
    op.add_column('inventory_transactions', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('inventory_transactions', sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('inventory_transactions', 'transaction_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('IN', 'OUT', 'TRANSFER', 'RETURN', 'ALLOCATION', 'RELEASE', 'ADJUSTMENT', name='transactiontype'),
               existing_nullable=False)
    op.create_index(op.f('ix_inventory_transactions_material_id'), 'inventory_transactions', ['material_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_transaction_type'), 'inventory_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_warehouse_id'), 'inventory_transactions', ['warehouse_id'], unique=False)
    op.create_unique_constraint(None, 'inventory_transactions', ['transaction_number'])
    op.drop_constraint(op.f('inventory_transactions_warehouse_id_fkey'), 'inventory_transactions', type_='foreignkey')
    op.drop_constraint(op.f('inventory_transactions_material_id_fkey'), 'inventory_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'inventory_transactions', 'materials', ['material_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'inventory_transactions', 'warehouses', ['warehouse_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_column('inventory_transactions', 'description')
    op.drop_column('inventory_transactions', 'created_by')
    op.add_column('material_requests', sa.Column('requested_by', sa.String(length=255), nullable=True))
    op.add_column('material_requests', sa.Column('approved_by', sa.String(length=255), nullable=True))
    op.add_column('material_requests', sa.Column('quantity_requested', sa.Float(), nullable=False))
    op.add_column('material_requests', sa.Column('quantity_allocated', sa.Float(), nullable=False))
    op.add_column('material_requests', sa.Column('request_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'ALLOCATED', 'ISSUED', 'COMPLETED', name='requeststatus'), nullable=False))
    op.add_column('material_requests', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('material_requests', sa.Column('request_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('material_requests', sa.Column('approval_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('material_requests', sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_material_requests_request_number'), table_name='material_requests')
    op.create_index(op.f('ix_material_requests_material_id'), 'material_requests', ['material_id'], unique=False)
    op.create_index(op.f('ix_material_requests_request_status'), 'material_requests', ['request_status'], unique=False)
    op.create_unique_constraint(None, 'material_requests', ['request_number'])
    op.drop_constraint(op.f('material_requests_warehouse_id_fkey'), 'material_requests', type_='foreignkey')
    op.drop_constraint(op.f('material_requests_material_id_fkey'), 'material_requests', type_='foreignkey')
    op.create_foreign_key(None, 'material_requests', 'materials', ['material_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_column('material_requests', 'required_quantity')
    op.drop_column('material_requests', 'approved_quantity')
    op.drop_column('material_requests', 'status')
    op.drop_column('material_requests', 'shortage_quantity')
    op.drop_column('material_requests', 'warehouse_id')
    op.drop_column('material_requests', 'reviewed_by')
    op.drop_column('material_requests', 'created_by')
    op.drop_index(op.f('ix_material_reservations_reservation_number'), table_name='material_reservations')
    op.create_unique_constraint(None, 'material_reservations', ['reservation_number'])
    op.drop_constraint(op.f('material_reservations_warehouse_id_fkey'), 'material_reservations', type_='foreignkey')
    op.drop_constraint(op.f('material_reservations_material_id_fkey'), 'material_reservations', type_='foreignkey')
    op.create_foreign_key(None, 'material_reservations', 'materials', ['material_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'material_reservations', 'warehouses', ['warehouse_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.add_column('materials', sa.Column('item_code', sa.String(length=100), nullable=False))
    op.add_column('materials', sa.Column('item_name', sa.String(length=255), nullable=False))
    op.add_column('materials', sa.Column('sub_category', sa.String(length=100), nullable=True))
    op.add_column('materials', sa.Column('grade', sa.String(length=100), nullable=True))
    op.add_column('materials', sa.Column('specification', sa.String(length=255), nullable=True))
    op.add_column('materials', sa.Column('dimensions', sa.String(length=100), nullable=True))
    op.add_column('materials', sa.Column('unit', sa.String(length=50), nullable=False))
    op.add_column('materials', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('materials', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('materials', sa.Column('barcode', sa.String(length=255), nullable=True))
    op.add_column('materials', sa.Column('qr_code', sa.String(length=255), nullable=True))
    op.add_column('materials', sa.Column('status', sa.Enum('AVAILABLE', 'LOW_STOCK', 'OUT_OF_STOCK', 'INACTIVE', name='materialstatus'), nullable=False))
    op.add_column('materials', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_materials_sku'), table_name='materials')
    op.create_index(op.f('ix_materials_category'), 'materials', ['category'], unique=False)
    op.create_index(op.f('ix_materials_item_code'), 'materials', ['item_code'], unique=True)
    op.create_index(op.f('ix_materials_item_name'), 'materials', ['item_name'], unique=False)
    op.drop_constraint(op.f('materials_supplier_id_fkey'), 'materials', type_='foreignkey')
    op.drop_column('materials', 'name')
    op.drop_column('materials', 'sku')
    op.drop_column('materials', 'supplier_id')
    op.add_column('warehouses', sa.Column('warehouse_code', sa.String(length=100), nullable=False))
    op.add_column('warehouses', sa.Column('warehouse_name', sa.String(length=255), nullable=False))
    op.add_column('warehouses', sa.Column('manager', sa.String(length=255), nullable=True))
    op.add_column('warehouses', sa.Column('capacity', sa.Float(), nullable=True))
    op.add_column('warehouses', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='warehousestatus'), nullable=False))
    op.alter_column('warehouses', 'location',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index(op.f('ix_warehouses_name'), table_name='warehouses')
    op.create_unique_constraint(None, 'warehouses', ['warehouse_code'])
    op.drop_column('warehouses', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'warehouses', type_='unique')
    op.create_index(op.f('ix_warehouses_name'), 'warehouses', ['name'], unique=True)
    op.alter_column('warehouses', 'location',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('warehouses', 'status')
    op.drop_column('warehouses', 'capacity')
    op.drop_column('warehouses', 'manager')
    op.drop_column('warehouses', 'warehouse_name')
    op.drop_column('warehouses', 'warehouse_code')
    op.add_column('materials', sa.Column('supplier_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('materials', sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('materials', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('materials_supplier_id_fkey'), 'materials', 'suppliers', ['supplier_id'], ['id'])
    op.drop_index(op.f('ix_materials_item_name'), table_name='materials')
    op.drop_index(op.f('ix_materials_item_code'), table_name='materials')
    op.drop_index(op.f('ix_materials_category'), table_name='materials')
    op.create_index(op.f('ix_materials_sku'), 'materials', ['sku'], unique=True)
    op.drop_column('materials', 'is_deleted')
    op.drop_column('materials', 'status')
    op.drop_column('materials', 'qr_code')
    op.drop_column('materials', 'barcode')
    op.drop_column('materials', 'image_url')
    op.drop_column('materials', 'description')
    op.drop_column('materials', 'unit')
    op.drop_column('materials', 'dimensions')
    op.drop_column('materials', 'specification')
    op.drop_column('materials', 'grade')
    op.drop_column('materials', 'sub_category')
    op.drop_column('materials', 'item_name')
    op.drop_column('materials', 'item_code')
    op.drop_constraint(None, 'material_reservations', type_='foreignkey')
    op.drop_constraint(None, 'material_reservations', type_='foreignkey')
    op.create_foreign_key(op.f('material_reservations_material_id_fkey'), 'material_reservations', 'materials', ['material_id'], ['id'])
    op.create_foreign_key(op.f('material_reservations_warehouse_id_fkey'), 'material_reservations', 'warehouses', ['warehouse_id'], ['id'])
    op.drop_constraint(None, 'material_reservations', type_='unique')
    op.create_index(op.f('ix_material_reservations_reservation_number'), 'material_reservations', ['reservation_number'], unique=True)
    op.add_column('material_requests', sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('material_requests', sa.Column('reviewed_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('material_requests', sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('material_requests', sa.Column('shortage_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('material_requests', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('material_requests', sa.Column('approved_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('material_requests', sa.Column('required_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'material_requests', type_='foreignkey')
    op.create_foreign_key(op.f('material_requests_material_id_fkey'), 'material_requests', 'materials', ['material_id'], ['id'])
    op.create_foreign_key(op.f('material_requests_warehouse_id_fkey'), 'material_requests', 'warehouses', ['warehouse_id'], ['id'])
    op.drop_constraint(None, 'material_requests', type_='unique')
    op.drop_index(op.f('ix_material_requests_request_status'), table_name='material_requests')
    op.drop_index(op.f('ix_material_requests_material_id'), table_name='material_requests')
    op.create_index(op.f('ix_material_requests_request_number'), 'material_requests', ['request_number'], unique=True)
    op.drop_column('material_requests', 'issue_date')
    op.drop_column('material_requests', 'approval_date')
    op.drop_column('material_requests', 'request_date')
    op.drop_column('material_requests', 'remarks')
    op.drop_column('material_requests', 'request_status')
    op.drop_column('material_requests', 'quantity_allocated')
    op.drop_column('material_requests', 'quantity_requested')
    op.drop_column('material_requests', 'approved_by')
    op.drop_column('material_requests', 'requested_by')
    op.add_column('inventory_transactions', sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('inventory_transactions', sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_transactions_material_id_fkey'), 'inventory_transactions', 'materials', ['material_id'], ['id'])
    op.create_foreign_key(op.f('inventory_transactions_warehouse_id_fkey'), 'inventory_transactions', 'warehouses', ['warehouse_id'], ['id'])
    op.drop_constraint(None, 'inventory_transactions', type_='unique')
    op.drop_index(op.f('ix_inventory_transactions_warehouse_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_transaction_type'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_material_id'), table_name='inventory_transactions')
    op.alter_column('inventory_transactions', 'transaction_type',
               existing_type=sa.Enum('IN', 'OUT', 'TRANSFER', 'RETURN', 'ALLOCATION', 'RELEASE', 'ADJUSTMENT', name='transactiontype'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('inventory_transactions', 'transaction_date')
    op.drop_column('inventory_transactions', 'remarks')
    op.drop_column('inventory_transactions', 'performed_by')
    op.drop_column('inventory_transactions', 'transaction_number')
    op.add_column('inventory', sa.Column('warehouse_location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('inventory', sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_material_id_fkey'), 'inventory', 'materials', ['material_id'], ['id'])
    op.drop_constraint('uq_inventory_material_warehouse', 'inventory', type_='unique')
    op.drop_index(op.f('ix_inventory_warehouse_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_material_id'), table_name='inventory')
    op.create_unique_constraint(op.f('inventory_material_id_key'), 'inventory', ['material_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('inventory', 'last_stock_update')
    op.drop_column('inventory', 'unit_cost')
    op.drop_column('inventory', 'storage_location')
    op.drop_column('inventory', 'reorder_level')
    op.drop_column('inventory', 'maximum_stock')
    op.drop_column('inventory', 'minimum_stock')
    op.drop_column('inventory', 'reserved_quantity')
    op.drop_column('inventory', 'available_quantity')
    op.drop_column('inventory', 'warehouse_id')
    op.drop_constraint(None, 'goods_receipts', type_='foreignkey')
    op.create_foreign_key(op.f('goods_receipts_warehouse_id_fkey'), 'goods_receipts', 'warehouses', ['warehouse_id'], ['id'])
    op.drop_constraint(None, 'goods_receipts', type_='unique')
    op.create_index(op.f('ix_goods_receipts_grn_number'), 'goods_receipts', ['grn_number'], unique=True)
    op.drop_constraint(None, 'goods_receipt_items', type_='foreignkey')
    op.create_foreign_key(op.f('goods_receipt_items_material_id_fkey'), 'goods_receipt_items', 'materials', ['material_id'], ['id'])
    op.alter_column('goods_receipt_items', 'rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_table('production_jobs',
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('supervisor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('production_jobs_project_id_fkey')),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], name=op.f('production_jobs_supervisor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('production_jobs_pkey'))
    )
    op.create_index(op.f('ix_production_jobs_id'), 'production_jobs', ['id'], unique=False)
    op.create_table('inventory_stock',
    sa.Column('material_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('current_stock', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reserved_stock', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('issued_stock', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('low_stock_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('inventory_stock_material_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('inventory_stock_warehouse_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_stock_pkey')),
    sa.UniqueConstraint('material_id', 'warehouse_id', name=op.f('_material_warehouse_uc'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_inventory_stock_id'), 'inventory_stock', ['id'], unique=False)
    op.create_table('suppliers',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('suppliers_pkey'))
    )
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.drop_index(op.f('ix_material_allocation_logs_warehouse_id'), table_name='material_allocation_logs')
    op.drop_index(op.f('ix_material_allocation_logs_material_id'), table_name='material_allocation_logs')
    op.drop_index(op.f('ix_material_allocation_logs_id'), table_name='material_allocation_logs')
    op.drop_table('material_allocation_logs')
    # ### end Alembic commands ###
