"""Add Module 4 dispatch models

Revision ID: 71f1ebf65925
Revises: 4db996dd2e5a
Create Date: 2026-07-14 21:44:32.552120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71f1ebf65925'
down_revision: Union[str, Sequence[str], None] = '4db996dd2e5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch_recommendations',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('dispatch_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('business_benefit', sa.String(length=1000), nullable=True),
    sa.Column('possible_risk', sa.String(length=1000), nullable=True),
    sa.Column('dispatch_priority', sa.String(length=50), nullable=False),
    sa.Column('estimated_trailer_category', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_recommendations_id'), 'dispatch_recommendations', ['id'], unique=False)
    op.create_table('dispatch_batches',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('total_weight_tons', sa.Float(), nullable=False),
    sa.Column('total_volume_m3', sa.Float(), nullable=False),
    sa.Column('estimated_trailer_category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['dispatch_recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_batches_id'), 'dispatch_batches', ['id'], unique=False)
    op.create_table('dispatch_batch_tickets',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['dispatch_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_batch_tickets_id'), 'dispatch_batch_tickets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispatch_batch_tickets_id'), table_name='dispatch_batch_tickets')
    op.drop_table('dispatch_batch_tickets')
    op.drop_index(op.f('ix_dispatch_batches_id'), table_name='dispatch_batches')
    op.drop_table('dispatch_batches')
    op.drop_index(op.f('ix_dispatch_recommendations_id'), table_name='dispatch_recommendations')
    op.drop_table('dispatch_recommendations')
    # ### end Alembic commands ###
