"""Add UserRole and ProjectAssignment

Revision ID: 8c6218e0d8f9
Revises: 71f1ebf65925
Create Date: 2026-07-21 10:47:42.517098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c6218e0d8f9'
down_revision: Union[str, Sequence[str], None] = '71f1ebf65925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_assignments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('assignment_role', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_assignments_id'), 'project_assignments', ['id'], unique=False)
    op.drop_index(op.f('ix_material_requests_id'), table_name='material_requests')
    op.drop_index(op.f('ix_material_requests_request_number'), table_name='material_requests')
    op.drop_table('material_requests')
    op.drop_index(op.f('ix_goods_receipts_grn_number'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_id'), table_name='goods_receipts')
    op.drop_table('goods_receipts')
    op.drop_index(op.f('ix_inventory_transactions_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_inventory_stock_id'), table_name='inventory_stock')
    op.drop_table('inventory_stock')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_name'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_material_reservations_id'), table_name='material_reservations')
    op.drop_index(op.f('ix_material_reservations_reservation_number'), table_name='material_reservations')
    op.drop_table('material_reservations')
    op.drop_index(op.f('ix_goods_receipt_items_id'), table_name='goods_receipt_items')
    op.drop_table('goods_receipt_items')
    op.drop_column('materials', 'unit')
    op.drop_column('materials', 'is_active')
    op.drop_column('materials', 'description')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SUPER_ADMIN', 'PROJECT_MANAGER', 'INVENTORY_MANAGER', 'CLIENT', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('SUPER_ADMIN', 'PROJECT_MANAGER', 'INVENTORY_MANAGER', 'CLIENT', name='userrole'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('materials', sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('materials', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('materials', sa.Column('unit', sa.VARCHAR(length=50), server_default=sa.text("'pcs'::character varying"), autoincrement=False, nullable=True))
    op.create_table('goods_receipt_items',
    sa.Column('goods_receipt_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('material_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipts.id'], name=op.f('goods_receipt_items_goods_receipt_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('goods_receipt_items_material_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('goods_receipt_items_pkey'))
    )
    op.create_index(op.f('ix_goods_receipt_items_id'), 'goods_receipt_items', ['id'], unique=False)
    op.create_table('material_reservations',
    sa.Column('reservation_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('material_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reserved_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reserved_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('material_reservations_material_id_fkey')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('material_reservations_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('material_reservations_pkey'))
    )
    op.create_index(op.f('ix_material_reservations_reservation_number'), 'material_reservations', ['reservation_number'], unique=True)
    op.create_index(op.f('ix_material_reservations_id'), 'material_reservations', ['id'], unique=False)
    op.create_table('warehouses',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('warehouses_pkey'))
    )
    op.create_index(op.f('ix_warehouses_name'), 'warehouses', ['name'], unique=True)
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_table('inventory_stock',
    sa.Column('material_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('current_stock', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reserved_stock', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('issued_stock', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('low_stock_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('inventory_stock_material_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('inventory_stock_warehouse_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_stock_pkey')),
    sa.UniqueConstraint('material_id', 'warehouse_id', name=op.f('_material_warehouse_uc'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_inventory_stock_id'), 'inventory_stock', ['id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('transaction_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('reference_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('material_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('inventory_transactions_material_id_fkey')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('inventory_transactions_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_transactions_pkey'))
    )
    op.create_index(op.f('ix_inventory_transactions_id'), 'inventory_transactions', ['id'], unique=False)
    op.create_table('goods_receipts',
    sa.Column('grn_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('supplier', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('received_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('received_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('goods_receipts_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('goods_receipts_pkey'))
    )
    op.create_index(op.f('ix_goods_receipts_id'), 'goods_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_goods_receipts_grn_number'), 'goods_receipts', ['grn_number'], unique=True)
    op.create_table('material_requests',
    sa.Column('request_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('material_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('required_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('shortage_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('approved_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('material_requests_material_id_fkey')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('material_requests_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('material_requests_pkey'))
    )
    op.create_index(op.f('ix_material_requests_request_number'), 'material_requests', ['request_number'], unique=True)
    op.create_index(op.f('ix_material_requests_id'), 'material_requests', ['id'], unique=False)
    op.drop_index(op.f('ix_project_assignments_id'), table_name='project_assignments')
    op.drop_table('project_assignments')
    # ### end Alembic commands ###
